"""Build the fiddler crab: high poly, game mesh (~25k tris), UVs, bakes, textures.

Run headless (Blender 5.2 LTS):
  blender -b --factory-startup --python-exit-code 1 --python Art/blender/build_crab.py -- [--stage all|model|bake]

Stages
  model : procedural parts -> game mesh + UV atlas + high poly (subdivision + displacement)
          saved to Art/blender/_work/crab_model.blend
  bake  : Cycles CPU bakes (normal, AO, data maps) -> hand-painted BaseColor / Normal / ORM PNGs
          in Art/export/textures, and Art/blender/_work/crab_lowpoly.blend (game mesh + material)

Everything here is original work generated by code. No external assets.
"""
import os
import sys
import time
import math
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import crab_lib as L  # noqa: E402

try:
    import bpy  # noqa: E402
except ImportError:  # allow importing for the spec only
    bpy = None

ATLAS = 2048


# ------------------------------------------------------------------ atlas --
class MaxRects:
    def __init__(self, w, h):
        self.free = [(0, 0, w, h)]

    def insert(self, w, h, allow_rot=True):
        best = None
        for (fx, fy, fw, fh) in self.free:
            for (rw, rh, rot) in ((w, h, False), (h, w, True)) if allow_rot else ((w, h, False),):
                if rw <= fw and rh <= fh:
                    sc = (min(fw - rw, fh - rh), max(fw - rw, fh - rh))
                    if best is None or sc < best[0]:
                        best = (sc, fx, fy, rw, rh, rot)
        if best is None:
            return None
        _, x, y, rw, rh, rot = best
        new_free = []
        for (fx, fy, fw, fh) in self.free:
            if x >= fx + fw or x + rw <= fx or y >= fy + fh or y + rh <= fy:
                new_free.append((fx, fy, fw, fh))
                continue
            if x > fx:
                new_free.append((fx, fy, x - fx, fh))
            if x + rw < fx + fw:
                new_free.append((x + rw, fy, fx + fw - x - rw, fh))
            if y > fy:
                new_free.append((fx, fy, fw, y - fy))
            if y + rh < fy + fh:
                new_free.append((fx, y + rh, fw, fy + fh - y - rh))
        pruned = []
        for i, a in enumerate(new_free):
            contained = False
            for j, c in enumerate(new_free):
                if i != j and a[0] >= c[0] and a[1] >= c[1] and a[0] + a[2] <= c[0] + c[2] and a[1] + a[3] <= c[1] + c[3]:
                    if a != c or i > j:
                        contained = True
                        break
            if not contained:
                pruned.append(a)
        self.free = pruned
        return x, y, rot


def pack_atlas(parts, size=ATLAS, pad=10):
    """Rectangle-pack every UV island (with 90 degree rotation) into the atlas.
    Returns {(part_index, island): (u0, v0, x, y, scale, rotated, vmax)} and the px/m scale."""
    islands = []
    for pi, p in enumerate(parts):
        by = {}
        for uvs, isl in zip(p.UV, p.isl):
            by.setdefault(isl, []).extend(uvs)
        for isl, uvs in by.items():
            arr = np.array(uvs)
            mn, mx = arr.min(0), arr.max(0)
            islands.append(dict(pi=pi, isl=isl, u0=mn[0], v0=mn[1], w=mx[0] - mn[0], h=mx[1] - mn[1], wt=p.uvw,
                                vmax=mx[1]))

    def attempt(scale):
        mr = MaxRects(size, size)
        items = sorted(islands, key=lambda i: -(i["w"] * i["h"] * i["wt"] ** 2))
        placed = []
        for it in items:
            sc = scale * it["wt"]
            w = int(math.ceil(it["w"] * sc)) + 2 * pad
            h = int(math.ceil(it["h"] * sc)) + 2 * pad
            r = mr.insert(w, h, True)
            if r is None:
                return False, None
            placed.append((it, r[0] + pad, r[1] + pad, sc, r[2]))
        return True, placed

    lo, hi = 50.0, 4000.0
    for _ in range(30):
        mid = (lo + hi) / 2
        ok, _p = attempt(mid)
        if ok:
            lo = mid
        else:
            hi = mid
    ok, placed = attempt(lo)
    table = {}
    for it, x, y, sc, rot in placed:
        table[(it["pi"], it["isl"])] = (it["u0"], it["v0"], x, y, sc, rot, it["w"], it["h"])
    return table, lo


def map_uv(entry, u, v):
    u0, v0, x, y, sc, rot, w, h = entry
    du, dv = u - u0, v - v0
    if rot:
        # rotate 90 deg: (du,dv) -> (h - dv, du)
        px, py = x + (h - dv) * sc, y + du * sc
    else:
        px, py = x + du * sc, y + dv * sc
    return px / ATLAS, py / ATLAS


# ------------------------------------------------------- blender helpers ---
def clear_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)


def parts_to_object(parts, name, atlas=None, with_attrs=True):
    Vs, Fs, UVs = [], [], []
    pid, pd, part_index = [], [], []
    off = 0
    for pi, p in enumerate(parts):
        Vs.append(p.V)
        for f in p.F:
            Fs.append(tuple(i + off for i in f))
        if atlas is not None:
            for uvs, isl in zip(p.UV, p.isl):
                ent = atlas[(pi, isl)]
                for (u, v) in uvs:
                    UVs.append(map_uv(ent, u, v))
        pid.append(np.full(len(p.V), float(p.pid)))
        sp = p.sp if p.sp is not None else np.zeros(len(p.V))
        cs = p.cs if p.cs is not None else np.zeros((len(p.V), 2))
        pd.append(np.column_stack([sp, cs]))
        part_index.append(np.full(len(p.V), pi))
        off += len(p.V)
    V = np.vstack(Vs)
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(V.tolist(), [], Fs)
    mesh.update()
    if atlas is not None:
        uvl = mesh.uv_layers.new(name="UVMap")
        uvl.data.foreach_set("uv", np.array(UVs, dtype=np.float32).ravel())
    if with_attrs:
        a = mesh.attributes.new("pid", 'FLOAT', 'POINT')
        a.data.foreach_set("value", np.concatenate(pid).astype(np.float32))
        b = mesh.attributes.new("pd", 'FLOAT_VECTOR', 'POINT')
        b.data.foreach_set("vector", np.vstack(pd).astype(np.float32).ravel())
    mesh.polygons.foreach_set("use_smooth", np.ones(len(mesh.polygons), dtype=bool))
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.scene.collection.objects.link(obj)
    return obj


def make_high(parts):
    """Subdivide every part and displace it: the high poly used for baking."""
    import crab_detail as D
    bpy.context.view_layer.update()
    objs = []
    t0 = time.time()
    for p in parts:
        ob = parts_to_object([p], "hp_" + p.name, atlas=None)
        mod = ob.modifiers.new("sub", 'SUBSURF')
        mod.levels = p.sub
        mod.render_levels = p.sub
        dg = bpy.context.evaluated_depsgraph_get()
        ev = ob.evaluated_get(dg)
        me = bpy.data.meshes.new_from_object(ev)
        n = len(me.vertices)
        co = np.empty(n * 3, np.float32)
        me.vertices.foreach_get("co", co)
        co = co.reshape(-1, 3).astype(np.float64)
        nr = np.empty(n * 3, np.float32)
        me.vertex_normals.foreach_get("vector", nr)
        nr = nr.reshape(-1, 3).astype(np.float64)
        pd = np.empty(n * 3, np.float32)
        me.attributes["pd"].data.foreach_get("vector", pd)
        pd = pd.reshape(-1, 3)
        p.sp_hi = pd[:, 0].astype(np.float64)
        p.cs_hi = pd[:, 1:3].astype(np.float64)
        h = D.displace(p, co, nr).astype(np.float32)
        co2 = co + nr * h[:, None]
        me.vertices.foreach_set("co", co2.astype(np.float32).ravel())
        ha = me.attributes.new("hdisp", 'FLOAT', 'POINT')
        ha.data.foreach_set("value", h)
        me.update()
        bpy.data.objects.remove(ob)
        nob = bpy.data.objects.new("hi_" + p.name, me)
        me.name = "hi_" + p.name
        bpy.context.scene.collection.objects.link(nob)
        objs.append(nob)
        print(f"   high {p.name:20s} sub={p.sub} verts={n:7d} hmin={h.min()*1000:6.2f}mm hmax={h.max()*1000:6.2f}mm")
    tot_f = sum(len(o.data.polygons) for o in objs)
    tot_v = sum(len(o.data.vertices) for o in objs)
    print(f"[model] high poly: {len(objs)} part objects, {tot_f} faces, {tot_v} verts ({time.time()-t0:.1f}s)")
    return objs


def stage_model(q=None):
    t0 = time.time()
    clear_scene()
    parts = L.build_all(q)
    tris = L.tri_count(parts)
    print(f"[model] parts={len(parts)} tris={tris}")
    for p in parts:
        print(f"   {p.name:22s} pid={p.pid:2d} verts={len(p.V):5d} tris={sum(len(f)-2 for f in p.F):5d}")
    atlas, scale = pack_atlas(parts)
    print(f"[model] atlas scale {scale:.0f} px/m")
    low = parts_to_object(parts, "crab_low", atlas)
    m = bpy.data.materials.new("MI_FiddlerCrab")
    m.use_nodes = True
    low.data.materials.append(m)
    if "--nohigh" not in sys.argv:
        make_high(parts)
    os.makedirs(L.WORK, exist_ok=True)
    bpy.ops.wm.save_as_mainfile(filepath=os.path.join(L.WORK, "crab_model.blend"))
    print(f"[model] done in {time.time()-t0:.1f}s")
    return parts


# ------------------------------------------------------------------- bake --
def new_image(name, float_buf=True):
    img = bpy.data.images.new(name, ATLAS, ATLAS, alpha=False, float_buffer=float_buf, is_data=True)
    img.colorspace_settings.name = 'Non-Color'
    return img


def clear_nodes(mat, keep=("BAKE_TARGET",)):
    nt = mat.node_tree
    for n in list(nt.nodes):
        if n.name not in keep:
            nt.nodes.remove(n)


def set_target(mat, img):
    nt = mat.node_tree
    node = nt.nodes.get("BAKE_TARGET")
    if node is None:
        node = nt.nodes.new('ShaderNodeTexImage')
        node.name = "BAKE_TARGET"
    node.image = img
    for n in nt.nodes:
        n.select = False
    node.select = True
    nt.nodes.active = node


def emission_material(mat, source, attr=None, scale=1.0):
    """Wire an emission shader that outputs a data channel (for baking data maps)."""
    clear_nodes(mat)
    nt = mat.node_tree
    out = nt.nodes.new('ShaderNodeOutputMaterial')
    em = nt.nodes.new('ShaderNodeEmission')
    nt.links.new(em.outputs['Emission'], out.inputs['Surface'])
    if source == 'pos':
        g = nt.nodes.new('ShaderNodeNewGeometry')
        nt.links.new(g.outputs['Position'], em.inputs['Color'])
    elif source == 'nrm':
        g = nt.nodes.new('ShaderNodeNewGeometry')
        nt.links.new(g.outputs['Normal'], em.inputs['Color'])
    elif source == 'vec':
        an = nt.nodes.new('ShaderNodeAttribute')
        an.attribute_name = attr
        an.attribute_type = 'GEOMETRY'
        nt.links.new(an.outputs['Vector'], em.inputs['Color'])
    elif source == 'fac':
        an = nt.nodes.new('ShaderNodeAttribute')
        an.attribute_name = attr
        an.attribute_type = 'GEOMETRY'
        cx = nt.nodes.new('ShaderNodeCombineXYZ')
        mul = nt.nodes.new('ShaderNodeMath')
        mul.operation = 'MULTIPLY'
        mul.inputs[1].default_value = scale
        nt.links.new(an.outputs['Fac'], mul.inputs[0])
        nt.links.new(mul.outputs[0], cx.inputs['X'])
        nt.links.new(cx.outputs['Vector'], em.inputs['Color'])
    out.is_active_output = True


def read_image(img):
    px = np.empty(ATLAS * ATLAS * 4, dtype=np.float32)
    img.pixels.foreach_get(px)
    return px.reshape(ATLAS, ATLAS, 4)


def stage_bake():
    """Bake data maps from the game mesh, then normal / height / AO from the high poly ONE PART AT A TIME:
    a part is only projected onto its own high poly, so interpenetrating limbs (arm through the carapace,
    legs into the hips) cannot leave ghost patches on the shell that show when the limb moves."""
    import bmesh
    t0 = time.time()
    bpy.ops.wm.open_mainfile(filepath=os.path.join(L.WORK, "crab_model.blend"))
    sc = bpy.context.scene
    low = bpy.data.objects["crab_low"]
    parts = L.build_all()
    his = {p.name: bpy.data.objects["hi_" + p.name] for p in parts}
    sc.render.engine = 'CYCLES'
    sc.cycles.device = 'CPU'
    sc.render.threads_mode = 'FIXED'
    sc.render.threads = 4
    sc.cycles.use_denoising = False
    mat = low.data.materials[0]
    mat.use_nodes = True

    def select(active, others=()):
        bpy.ops.object.select_all(action='DESELECT')
        for o in others:
            o.select_set(True)
        active.select_set(True)
        bpy.context.view_layer.objects.active = active

    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    only = set(argv[argv.index("--only") + 1].split(",")) if "--only" in argv else None
    maps = dict(np.load(os.path.join(L.WORK, "bake_maps.npz"))) if only else {}

    def bake_data(name, source, attr=None, scale=1.0, samples=1):
        img = new_image("bake_" + name)
        emission_material(mat, source, attr, scale)
        set_target(mat, img)
        select(low)
        sc.cycles.samples = samples
        bpy.ops.object.bake(type='EMIT', use_selected_to_active=False, margin=16, margin_type='EXTEND',
                            width=ATLAS, height=ATLAS)
        maps[name] = read_image(img)[..., :3].copy()
        bpy.data.images.remove(img)
        print(f"[bake] {name} done  ({time.time()-t0:.0f}s)")

    if not only:
        bake_data("pos", 'pos')
        bake_data("nrm", 'nrm')
        bake_data("pd", 'vec', 'pd')
        bake_data("pid", 'fac', 'pid', 1.0)
    pidmap = np.rint(maps["pid"][..., 0]).astype(np.int32)

    # emission of the displacement height on every high part
    hmat = bpy.data.materials.new("hi_mat")
    hmat.use_nodes = True
    emission_material(hmat, 'fac', 'hdisp', 100.0)     # centimetres
    for o in his.values():
        o.data.materials.clear()
        o.data.materials.append(hmat)

    # per-part low objects (same UVs, only that part's faces)
    ranges, o0 = [], 0
    for p in parts:
        ranges.append((o0, o0 + len(p.F)))
        o0 += len(p.F)

    def part_low(pi):
        ob = low.copy()
        ob.data = low.data.copy()
        ob.name = "lowpart"
        ob.hide_render = False
        ob.hide_viewport = False
        bpy.context.scene.collection.objects.link(ob)
        bm = bmesh.new()
        bm.from_mesh(ob.data)
        bm.faces.ensure_lookup_table()
        a, b_ = ranges[pi]
        bmesh.ops.delete(bm, geom=[f for f in bm.faces if not (a <= f.index < b_)], context='FACES')
        bm.to_mesh(ob.data)
        bm.free()
        return ob

    low.hide_render = True      # the full game mesh must not occlude the per-part AO rays (it coincides with the high poly)
    Hh = maps["h"].copy() if only else np.zeros((ATLAS, ATLAS), np.float32)
    Nn = maps["normal"].copy() if only else np.zeros((ATLAS, ATLAS, 3), np.float32)
    Ao = maps["ao"].copy() if only else np.ones((ATLAS, ATLAS), np.float32)
    w = bpy.data.worlds.new("bakeworld")
    w.use_nodes = True
    sc.world = w
    try:
        w.light_settings.distance = 0.30
    except Exception as e:  # pragma: no cover
        print("AO distance not settable:", e)
    common = dict(use_selected_to_active=True, cage_extrusion=0.02, max_ray_distance=0.03,
                  margin=16, margin_type='EXTEND', width=ATLAS, height=ATLAS)
    imgs = {k: new_image("bake_" + k) for k in ("h", "n", "ao")}
    for pi, p in enumerate(parts):
        if only and p.name not in only:
            continue
        lp = part_low(pi)
        hp = his[p.name]
        m = pidmap == p.pid
        # height
        emission_material(mat, 'pos')
        set_target(mat, imgs["h"])
        select(lp, [hp])
        sc.cycles.samples = 4
        bpy.ops.object.bake(type='EMIT', **common)
        Hh[m] = read_image(imgs["h"])[..., 0][m]
        # normal (tangent space, DirectX: green down)
        set_target(mat, imgs["n"])
        select(lp, [hp])
        sc.cycles.samples = 8
        bpy.ops.object.bake(type='NORMAL', normal_space='TANGENT', normal_r='POS_X', normal_g='NEG_Y', normal_b='POS_Z', **common)
        Nn[m] = read_image(imgs["n"])[..., :3][m]
        # ambient occlusion: the other parts stay in the scene as occluders, except that the shell ignores the limbs
        # that pierce it (texels inside a limb's cross-section would bake to solid black and show as dark discs once
        # the limb moves); crab_paint darkens the hip and shoulder sockets procedurally instead
        hidden = []
        if p.name == "carapace":
            for q in parts:
                if q.name != "carapace":
                    his[q.name].hide_render = True
                    hidden.append(his[q.name])
        set_target(mat, imgs["ao"])
        select(lp, [hp])
        sc.cycles.samples = 96
        bpy.ops.object.bake(type='AO', **common)
        Ao[m] = read_image(imgs["ao"])[..., 0][m]
        for o in hidden:
            o.hide_render = False
        bpy.data.objects.remove(lp)
        print(f"[bake] {p.name:20s} done ({time.time()-t0:.0f}s)")
    maps["h"] = Hh
    maps["normal"] = Nn
    maps["ao"] = Ao
    np.savez_compressed(os.path.join(L.WORK, "bake_maps.npz"), **maps)
    print(f"[bake] maps saved in {time.time()-t0:.0f}s")


# ------------------------------------------------------------------ paint --
def stage_paint():
    import crab_paint as PT
    t0 = time.time()
    maps = dict(np.load(os.path.join(L.WORK, "bake_maps.npz")))
    parts = L.build_all()
    color, rough, ao, valid = PT.paint_all(maps, parts)
    print(f"[paint] painted in {time.time()-t0:.0f}s")
    os.makedirs(L.TEX_DIR, exist_ok=True)
    c8 = (np.clip(color, 0, 1) * 255 + 0.5).astype(np.uint8)
    orm = np.stack([ao, rough, np.zeros_like(rough)], -1)
    o8 = (np.clip(orm, 0, 1) * 255 + 0.5).astype(np.uint8)
    nm = np.clip(maps["normal"], 0, 1).copy()
    nm[~valid] = (0.5, 0.5, 1.0)
    n8 = (nm * 255 + 0.5).astype(np.uint8)
    L.write_png(os.path.join(L.TEX_DIR, "T_FiddlerCrab_BaseColor.png"), c8[::-1])
    L.write_png(os.path.join(L.TEX_DIR, "T_FiddlerCrab_ORM.png"), o8[::-1])
    L.write_png(os.path.join(L.TEX_DIR, "T_FiddlerCrab_Normal.png"), n8[::-1])
    print(f"[paint] textures written ({time.time()-t0:.0f}s)")


def make_material(mat):
    """Preview/game shader: BaseColor + ORM + DirectX normal, slot name MI_FiddlerCrab."""
    mat.use_nodes = True
    nt = mat.node_tree
    for n in list(nt.nodes):
        nt.nodes.remove(n)
    out = nt.nodes.new('ShaderNodeOutputMaterial')
    bsdf = nt.nodes.new('ShaderNodeBsdfPrincipled')
    nt.links.new(bsdf.outputs['BSDF'], out.inputs['Surface'])

    def tex(name, cs):
        t = nt.nodes.new('ShaderNodeTexImage')
        img = bpy.data.images.load(os.path.join(L.TEX_DIR, name), check_existing=True)
        img.colorspace_settings.name = cs
        t.image = img
        t.interpolation = 'Linear'
        return t

    tb = tex("T_FiddlerCrab_BaseColor.png", 'sRGB')
    to = tex("T_FiddlerCrab_ORM.png", 'Non-Color')
    tn = tex("T_FiddlerCrab_Normal.png", 'Non-Color')
    sep = nt.nodes.new('ShaderNodeSeparateColor')
    nt.links.new(to.outputs['Color'], sep.inputs['Color'])
    mulao = nt.nodes.new('ShaderNodeMix')
    mulao.data_type = 'RGBA'
    mulao.blend_type = 'MULTIPLY'
    mulao.inputs['Factor'].default_value = 0.6
    nt.links.new(tb.outputs['Color'], mulao.inputs['A'])
    nt.links.new(sep.outputs['Red'], mulao.inputs['B'])
    nt.links.new(mulao.outputs['Result'], bsdf.inputs['Base Color'])
    nt.links.new(sep.outputs['Green'], bsdf.inputs['Roughness'])
    nt.links.new(sep.outputs['Blue'], bsdf.inputs['Metallic'])
    nsep = nt.nodes.new('ShaderNodeSeparateColor')
    nt.links.new(tn.outputs['Color'], nsep.inputs['Color'])
    inv = nt.nodes.new('ShaderNodeMath')
    inv.operation = 'SUBTRACT'
    inv.inputs[0].default_value = 1.0
    nt.links.new(nsep.outputs['Green'], inv.inputs[1])
    ncomb = nt.nodes.new('ShaderNodeCombineColor')
    nt.links.new(nsep.outputs['Red'], ncomb.inputs['Red'])
    nt.links.new(inv.outputs[0], ncomb.inputs['Green'])
    nt.links.new(nsep.outputs['Blue'], ncomb.inputs['Blue'])
    nmap = nt.nodes.new('ShaderNodeNormalMap')
    nt.links.new(ncomb.outputs['Color'], nmap.inputs['Color'])
    nt.links.new(nmap.outputs['Normal'], bsdf.inputs['Normal'])
    for k in ('Specular IOR Level',):
        if k in bsdf.inputs:
            bsdf.inputs[k].default_value = 0.5
    return mat


def stage_lowblend():
    """Game mesh + final material, saved for the rig script."""
    bpy.ops.wm.open_mainfile(filepath=os.path.join(L.WORK, "crab_model.blend"))
    for o in [o for o in bpy.data.objects if o.name.startswith("hi_") or o.name.startswith("crab_high")]:
        bpy.data.objects.remove(o)
    low = bpy.data.objects["crab_low"]
    mat = low.data.materials[0]
    mat.name = "MI_FiddlerCrab"
    make_material(mat)
    for img in list(bpy.data.images):
        if img.users == 0:
            bpy.data.images.remove(img)
    bpy.ops.wm.save_as_mainfile(filepath=os.path.join(L.WORK, "crab_lowpoly.blend"))
    print("[lowblend] saved crab_lowpoly.blend")


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    stage = "all"
    if "--stage" in argv:
        stage = argv[argv.index("--stage") + 1]
    if stage in ("model", "all"):
        stage_model()
    if stage in ("bake", "all"):
        stage_bake()
    if stage in ("paint", "all"):
        stage_paint()
    if stage in ("paint", "lowblend", "all"):
        stage_lowblend()


if __name__ == "__main__":
    main()
